package finalproj_test;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

import finalproj.Alien;
import finalproj.Capitan;
import finalproj.CrewMember;
import finalproj.CrewMemberAction;
import finalproj.Engineer;
import finalproj.Planet;
import finalproj.RandomEvent;
import finalproj.Resource;
import finalproj.Scientist;
import finalproj.SecurityOfficer;
import finalproj.SpaceEntity;
import finalproj.Starship;

public class GameDriver_test {

	public static void main(String[] args) {
		
		Scanner scanner = new Scanner(System.in);
		
		System.out.println("What would you like to do?: \n"
				+ "	1 - Test Normal Operation \n"
				+ "	2 - (Edge Case): Deplete Fuel and Attempt Travel\n"
				+ "	3 - (Corner Case): No Fuel and Un-winnable Combat\n"
				+ "	4 - (Edge Case): Exceed Cargo Capacity\n"
				+ "	5 - (Corner Case): All crewmember health at 0\n"
				+ "	6 - Excessive Randomness\n"
				+ "	7 - Quit \n");
		int choice = 0;
		
		try {
		    choice = scanner.nextInt();
		} catch (Exception e) {
		    System.out.println("Invalid input. Please enter a number between 1 and 4.");
		    scanner.nextLine(); // Clear the invalid input
		}

		if (choice < 1 || choice > 7) {
		    System.out.println("Invalid selection. Please choose a valid option.");
		}
		
		switch (choice) {
    	
	        case 1:
	    		testcase0(); //normal operation
	        	break;
	
	        case 2:
	    		testcase1(); //(Edge Case): Deplete Fuel and Attempt Travel
	            break;
	
	        case 3:
	    		testcase2(); //(Corner Case): No Fuel and Un-winnable Combat
	            break;
	
	        case 4:
	    		testcase4(); //(Edge Case): Exceed Cargo Capacity
	            break;
	            
	        case 5:
	    		testcase5(); //
	            break;
	            
			case 6:
				testcase6(); //Excessive Randomness
				break;
				
			case 7:
				System.out.println("Quitting Game Test...");
				break;

	
	        default:
	            // TODO: Handle input error
	        	break;
		}	
	}

	private static void testcase6() { // excessive randomness
		
		// 1. GAME INITIALIZATION
			
			//OBJECTS
			List<CrewMember> crew = new ArrayList<>();
			List<Planet> solarSystem = new ArrayList<>();
	        Scanner scanner = new Scanner(System.in);
	        RandomEvent event;
	        Random dice = new Random();
			//				shipName, fuelLevel(Liters), cargoCapacity(slots), hullIntegrity(%)
			Starship ship = new Starship("SS Latrexa", 1000, 10, 100);
			//				 name, strength(attkPwr), intellegence(x/10), agility(x/10), skill(x/20), health(%)
			CrewMember spock = new Capitan("Spock", 25, 8, 6, 18, 100);
			CrewMember travis = new SecurityOfficer("Travis", 60, 5, 9, 16, 100);
			CrewMember adam = new Engineer("Adam", 10, 9, 3, 20, 100);
			CrewMember taylor = new Scientist("Taylor", 15, 8, 4, 19, 100);
			//						planet name, description
			Planet neptune = new Planet("Neptune", "A storm-ridden gas giant with an endless sea of swirling green and violet "
					+ "clouds. The planet's gravity is so intense that its core is rumored to be a crystalline network of "
					+ "compressed elements, sought after for advanced technology. Lightning arcs across the skies, and "
					+ "floating mining stations cling perilously to its atmosphere.");
			Planet saturn = new Planet("Saturn", "A dazzling desert world with golden sands that shimmer under "
					+ "twin suns. Beneath its surface lie vast caverns filled with bioluminescent flora and crystalline "
					+ "rivers. The nomadic inhabitants harvest \"sunstones,\" rare minerals that store solar energy, "
					+ "making the planet a hub for energy traders.");
			Planet venus = new Planet("Venus", "A frozen tundra planet covered in glaciers and jagged ice peaks. "
					+ "Aurora-like light displays dance across the sky, generated by the planet's magnetized core. "
					+ "Ancient ruins buried deep within the ice suggest a long-lost civilization, and explorers "
					+ "come in search of the mysterious relics.");
			Planet mars = new Planet("Mars", "A lush jungle planet teeming with exotic, bioluminescent "
					+ "plants and colossal, sentient fungi. Its dense atmosphere glows faintly at night, "
					+ "illuminating the surface with hues of blue and purple. The native species, Kaelvans, "
					+ "are telepathic and fiercely protective of the planet’s natural balance.");
			Planet pluto = new Planet("Pluto", "A volcanic world with rivers of molten lava crisscrossing its "
					+ "surface. Ash clouds obscure its sky, and massive geysers release superheated steam. Despite its "
					+ "hostile environment, Vorrakis is rich in valuable ores and is home to fire-resistant creatures "
					+ "that thrive in the extreme heat.");

			//VARIABLES
			int locationIndex = 0;
			boolean gameExit = false;
	        String[] eventTypes = {"Plague", "Hull Damage", "Resource Theft", "Solar Flare"};
			
			//PRE-GAME ROUTINES
			crew.add(spock);
			crew.add(travis);
			crew.add(adam);
			crew.add(taylor);
			solarSystem.add(neptune);
			solarSystem.add(saturn);
			solarSystem.add(venus);
			solarSystem.add(mars);
			solarSystem.add(pluto);
			
		// 2. GAME-UPDATE LOOP
			
			System.out.println("Let your space adventure begin! All abourd the " + ship.getShipName() + "! \n");
			
			while (gameContinue((ArrayList<CrewMember>) crew, ship) && !gameExit) {
				
				System.out.println(displayStatus(crew, ship, solarSystem, locationIndex));
				
				System.out.println("What would you like to do?: \n"
						+ "	1 - Travel to another Planet \n"
						+ "	2 - Scan for resources on this planet \n"
						+ "	3 - Scan for lifeforms on this planet \n"
						+ "	4 - Quit \n");
				int choice;
				
				try {
				    choice = scanner.nextInt();
				} catch (Exception e) {
				    System.out.println("Invalid input. Please enter a number between 1 and 4.");
				    scanner.nextLine(); // Clear the invalid input
				    continue; // Restart the loop
				}

				if (choice < 1 || choice > 4) {
				    System.out.println("Invalid selection. Please choose a valid option.");
				    continue; // Restart the loop
				}
				
				switch (choice) {
		    	
			        case 1:
			            // Implement logic for travel
			        	locationIndex = travel(scanner, ship, locationIndex, solarSystem);
			        	event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
                        event.triggerEvent(event.getEventType(), ship, crew);
			        	break;
			
			        case 2:
			            // capitan scans the planet for resources
			        	((Capitan) crew.get(0)).action(crew, ship, solarSystem, locationIndex);
			        	event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
                        event.triggerEvent(event.getEventType(), ship, crew);
			            break;
			
			        case 3:
			            // Implement logic for lifeform scan
			        	((SecurityOfficer) crew.get(1)).action(crew, ship, solarSystem, locationIndex);
			        	event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
                        event.triggerEvent(event.getEventType(), ship, crew);
			            break;
			
			        case 4:
			            // Implement logic for break out of game entirely
			        	System.out.println("Exiting the game...");
			        	gameExit = true;
			            break;
			
			        default:
			            // TODO: Handle input error
			
			            break;
				}	
				//break;
			}
			
		// 3. GAME END
			scanner.close();
			System.out.println("GAME OVER");
			
	}

	private static void testcase5() { // the plague event is called to instantly kill everyone
		
		// 1. GAME INITIALIZATION
			
			//OBJECTS
			List<CrewMember> crew = new ArrayList<>();
			List<Planet> solarSystem = new ArrayList<>();
	        Scanner scanner = new Scanner(System.in);
	        RandomEvent event;
	        Random dice = new Random();
			//				shipName, fuelLevel(Liters), cargoCapacity(slots), hullIntegrity(%)
			Starship ship = new Starship("SS Latrexa", 1000, 10, 100);
			//				 name, strength(attkPwr), intellegence(x/10), agility(x/10), skill(x/20), health(%)
			CrewMember spock = new Capitan("Spock", 25, 8, 6, 18, 100);
			CrewMember travis = new SecurityOfficer("Travis", 60, 5, 9, 16, 100);
			CrewMember adam = new Engineer("Adam", 10, 9, 3, 20, 100);
			CrewMember taylor = new Scientist("Taylor", 15, 8, 4, 19, 100);
			//						planet name, description
			Planet neptune = new Planet("Neptune", "A storm-ridden gas giant with an endless sea of swirling green and violet "
					+ "clouds. The planet's gravity is so intense that its core is rumored to be a crystalline network of "
					+ "compressed elements, sought after for advanced technology. Lightning arcs across the skies, and "
					+ "floating mining stations cling perilously to its atmosphere.");
			Planet saturn = new Planet("Saturn", "A dazzling desert world with golden sands that shimmer under "
					+ "twin suns. Beneath its surface lie vast caverns filled with bioluminescent flora and crystalline "
					+ "rivers. The nomadic inhabitants harvest \"sunstones,\" rare minerals that store solar energy, "
					+ "making the planet a hub for energy traders.");
			Planet venus = new Planet("Venus", "A frozen tundra planet covered in glaciers and jagged ice peaks. "
					+ "Aurora-like light displays dance across the sky, generated by the planet's magnetized core. "
					+ "Ancient ruins buried deep within the ice suggest a long-lost civilization, and explorers "
					+ "come in search of the mysterious relics.");
			Planet mars = new Planet("Mars", "A lush jungle planet teeming with exotic, bioluminescent "
					+ "plants and colossal, sentient fungi. Its dense atmosphere glows faintly at night, "
					+ "illuminating the surface with hues of blue and purple. The native species, Kaelvans, "
					+ "are telepathic and fiercely protective of the planet’s natural balance.");
			Planet pluto = new Planet("Pluto", "A volcanic world with rivers of molten lava crisscrossing its "
					+ "surface. Ash clouds obscure its sky, and massive geysers release superheated steam. Despite its "
					+ "hostile environment, Vorrakis is rich in valuable ores and is home to fire-resistant creatures "
					+ "that thrive in the extreme heat.");

			//VARIABLES
			int locationIndex = 0;
			boolean gameExit = false;
	        String[] eventTypes = {"Plague", "Hull Damage", "Resource Theft", "Solar Flare"};
			
			//PRE-GAME ROUTINES
			crew.add(spock);
			crew.add(travis);
			crew.add(adam);
			crew.add(taylor);
			solarSystem.add(neptune);
			solarSystem.add(saturn);
			solarSystem.add(venus);
			solarSystem.add(mars);
			solarSystem.add(pluto);
			
		// 2. GAME-UPDATE LOOP
			
			System.out.println("Let your space adventure begin! All abourd the " + ship.getShipName() + "! \n");
			
			while (gameContinue((ArrayList<CrewMember>) crew, ship) && !gameExit) {
				
				System.out.println(displayStatus(crew, ship, solarSystem, locationIndex));
				
				System.out.println("What would you like to do?: \n"
						+ "	1 - Travel to another Planet \n"
						+ "	2 - Scan for resources on this planet \n"
						+ "	3 - Scan for lifeforms on this planet \n"
						+ "	4 - Quit \n");
				int choice;
				
				try {
				    choice = scanner.nextInt();
				} catch (Exception e) {
				    System.out.println("Invalid input. Please enter a number between 1 and 4.");
				    scanner.nextLine(); // Clear the invalid input
				    continue; // Restart the loop
				}

				if (choice < 1 || choice > 4) {
				    System.out.println("Invalid selection. Please choose a valid option.");
				    continue; // Restart the loop
				}
				
				switch (choice) {
		    	
			        case 1:
			            // Implement logic for travel
			        	locationIndex = travel(scanner, ship, locationIndex, solarSystem);
			        	event = new RandomEvent(eventTypes[0], "A random travel event occurred!");
                        event.triggerEvent(event.getEventType(), ship, crew);
			        	break;
			
			        case 2:
			            // capitan scans the planet for resources
			        	((Capitan) crew.get(0)).action(crew, ship, solarSystem, locationIndex);
			        	event = new RandomEvent(eventTypes[0], "A random travel event occurred!");
                        event.triggerEvent(event.getEventType(), ship, crew);
			            break;
			
			        case 3:
			            // Implement logic for lifeform scan
			        	((SecurityOfficer) crew.get(1)).action(crew, ship, solarSystem, locationIndex);
			        	event = new RandomEvent(eventTypes[0], "A random travel event occurred!");
                        event.triggerEvent(event.getEventType(), ship, crew);
			            break;
			
			        case 4:
			            // Implement logic for break out of game entirely
			        	System.out.println("Exiting the game...");
			        	gameExit = true;
			            break;
			
			        default:
			            // TODO: Handle input error
			
			            break;
				}	
				//break;
			}
			
		// 3. GAME END
			scanner.close();
			System.out.println("GAME OVER");
			
	}

	private static void testcase4() { // ship instantiates with a cargo capacity of 1
		
		// 1. GAME INITIALIZATION
			
			//OBJECTS
			List<CrewMember> crew = new ArrayList<>();
			List<Planet> solarSystem = new ArrayList<>();
	        Scanner scanner = new Scanner(System.in);
	        RandomEvent event;
	        Random dice = new Random();
			//				shipName, fuelLevel(Liters), cargoCapacity(slots), hullIntegrity(%)
			Starship ship = new Starship("SS Latrexa", 1000, 1, 100);
			//				 name, strength(attkPwr), intellegence(x/10), agility(x/10), skill(x/20), health(%)
			CrewMember spock = new Capitan("Spock", 25, 8, 6, 18, 100);
			CrewMember travis = new SecurityOfficer("Travis", 60, 5, 9, 16, 100);
			CrewMember adam = new Engineer("Adam", 10, 9, 3, 20, 100);
			CrewMember taylor = new Scientist("Taylor", 15, 8, 4, 19, 100);
			//						planet name, description
			Planet neptune = new Planet("Neptune", "A storm-ridden gas giant with an endless sea of swirling green and violet "
					+ "clouds. The planet's gravity is so intense that its core is rumored to be a crystalline network of "
					+ "compressed elements, sought after for advanced technology. Lightning arcs across the skies, and "
					+ "floating mining stations cling perilously to its atmosphere.");
			Planet saturn = new Planet("Saturn", "A dazzling desert world with golden sands that shimmer under "
					+ "twin suns. Beneath its surface lie vast caverns filled with bioluminescent flora and crystalline "
					+ "rivers. The nomadic inhabitants harvest \"sunstones,\" rare minerals that store solar energy, "
					+ "making the planet a hub for energy traders.");
			Planet venus = new Planet("Venus", "A frozen tundra planet covered in glaciers and jagged ice peaks. "
					+ "Aurora-like light displays dance across the sky, generated by the planet's magnetized core. "
					+ "Ancient ruins buried deep within the ice suggest a long-lost civilization, and explorers "
					+ "come in search of the mysterious relics.");
			Planet mars = new Planet("Mars", "A lush jungle planet teeming with exotic, bioluminescent "
					+ "plants and colossal, sentient fungi. Its dense atmosphere glows faintly at night, "
					+ "illuminating the surface with hues of blue and purple. The native species, Kaelvans, "
					+ "are telepathic and fiercely protective of the planet’s natural balance.");
			Planet pluto = new Planet("Pluto", "A volcanic world with rivers of molten lava crisscrossing its "
					+ "surface. Ash clouds obscure its sky, and massive geysers release superheated steam. Despite its "
					+ "hostile environment, Vorrakis is rich in valuable ores and is home to fire-resistant creatures "
					+ "that thrive in the extreme heat.");

			//VARIABLES
			int locationIndex = 0;
			boolean gameExit = false;
	        String[] eventTypes = {"Plague", "Hull Damage", "Resource Theft", "Solar Flare"};
			
			//PRE-GAME ROUTINES
			crew.add(spock);
			crew.add(travis);
			crew.add(adam);
			crew.add(taylor);
			solarSystem.add(neptune);
			solarSystem.add(saturn);
			solarSystem.add(venus);
			solarSystem.add(mars);
			solarSystem.add(pluto);
			
		// 2. GAME-UPDATE LOOP
			
			System.out.println("Let your space adventure begin! All abourd the " + ship.getShipName() + "! \n");
			
			while (gameContinue((ArrayList<CrewMember>) crew, ship) && !gameExit) {
				
				System.out.println(displayStatus(crew, ship, solarSystem, locationIndex));
				
				System.out.println("What would you like to do?: \n"
						+ "	1 - Travel to another Planet \n"
						+ "	2 - Scan for resources on this planet \n"
						+ "	3 - Scan for lifeforms on this planet \n"
						+ "	4 - Quit \n");
				int choice;
				
				try {
				    choice = scanner.nextInt();
				} catch (Exception e) {
				    System.out.println("Invalid input. Please enter a number between 1 and 4.");
				    scanner.nextLine(); // Clear the invalid input
				    continue; // Restart the loop
				}

				if (choice < 1 || choice > 4) {
				    System.out.println("Invalid selection. Please choose a valid option.");
				    continue; // Restart the loop
				}
				
				switch (choice) {
		    	
			        case 1:
			            // Implement logic for travel
			        	locationIndex = travel(scanner, ship, locationIndex, solarSystem);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			        	break;
			
			        case 2:
			            // capitan scans the planet for resources
			        	((Capitan) crew.get(0)).action(crew, ship, solarSystem, locationIndex);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			            break;
			
			        case 3:
			            // Implement logic for lifeform scan
			        	((SecurityOfficer) crew.get(1)).action(crew, ship, solarSystem, locationIndex);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			            break;
			
			        case 4:
			            // Implement logic for break out of game entirely
			        	System.out.println("Exiting the game...");
			        	gameExit = true;
			            break;
			
			        default:
			            // TODO: Handle input error
			
			            break;
				}	
				//break;
			}
			
		// 3. GAME END
			scanner.close();
			System.out.println("GAME OVER");
			
	}

	private static void testcase2() { // (ship starts with 0 fuel and Capitan class instantiates an alien with 500 health and 150 attkPwr)
		
		// 1. GAME INITIALIZATION 
			
			//OBJECTS
			List<CrewMember> crew = new ArrayList<>();
			List<Planet> solarSystem = new ArrayList<>();
	        Scanner scanner = new Scanner(System.in);
	        RandomEvent event;
	        Random dice = new Random();
			//				shipName, fuelLevel(Liters), cargoCapacity(slots), hullIntegrity(%)
			Starship ship = new Starship("SS Latrexa", 0, 10, 100);
			//				 name, strength(attkPwr), intellegence(x/10), agility(x/10), skill(x/20), health(%)
			CrewMember spock = new Capitan("Spock", 25, 8, 6, 18, 100);
			CrewMember travis = new SecurityOfficer("Travis", 60, 5, 9, 16, 100);
			CrewMember adam = new Engineer("Adam", 10, 9, 3, 20, 100);
			CrewMember taylor = new Scientist("Taylor", 15, 8, 4, 19, 100);
			//						planet name, description
			Planet neptune = new Planet("Neptune", "A storm-ridden gas giant with an endless sea of swirling green and violet "
					+ "clouds. The planet's gravity is so intense that its core is rumored to be a crystalline network of "
					+ "compressed elements, sought after for advanced technology. Lightning arcs across the skies, and "
					+ "floating mining stations cling perilously to its atmosphere.");
			Planet saturn = new Planet("Saturn", "A dazzling desert world with golden sands that shimmer under "
					+ "twin suns. Beneath its surface lie vast caverns filled with bioluminescent flora and crystalline "
					+ "rivers. The nomadic inhabitants harvest \"sunstones,\" rare minerals that store solar energy, "
					+ "making the planet a hub for energy traders.");
			Planet venus = new Planet("Venus", "A frozen tundra planet covered in glaciers and jagged ice peaks. "
					+ "Aurora-like light displays dance across the sky, generated by the planet's magnetized core. "
					+ "Ancient ruins buried deep within the ice suggest a long-lost civilization, and explorers "
					+ "come in search of the mysterious relics.");
			Planet mars = new Planet("Mars", "A lush jungle planet teeming with exotic, bioluminescent "
					+ "plants and colossal, sentient fungi. Its dense atmosphere glows faintly at night, "
					+ "illuminating the surface with hues of blue and purple. The native species, Kaelvans, "
					+ "are telepathic and fiercely protective of the planet’s natural balance.");
			Planet pluto = new Planet("Pluto", "A volcanic world with rivers of molten lava crisscrossing its "
					+ "surface. Ash clouds obscure its sky, and massive geysers release superheated steam. Despite its "
					+ "hostile environment, Vorrakis is rich in valuable ores and is home to fire-resistant creatures "
					+ "that thrive in the extreme heat.");

			//VARIABLES
			int locationIndex = 0;
			boolean gameExit = false;
	        String[] eventTypes = {"Plague", "Hull Damage", "Resource Theft", "Solar Flare"};
			
			//PRE-GAME ROUTINES
			crew.add(spock);
			crew.add(travis);
			crew.add(adam);
			crew.add(taylor);
			solarSystem.add(neptune);
			solarSystem.add(saturn);
			solarSystem.add(venus);
			solarSystem.add(mars);
			solarSystem.add(pluto);
			
		// 2. GAME-UPDATE LOOP
			
			System.out.println("Let your space adventure begin! All abourd the " + ship.getShipName() + "! \n");
			
			while (gameContinue((ArrayList<CrewMember>) crew, ship) && gameExit==false) {
				
				System.out.println(displayStatus(crew, ship, solarSystem, locationIndex));
				
				System.out.println("What would you like to do?: \n"
						+ "	1 - Travel to another Planet \n"
						+ "	2 - Scan for resources on this planet \n"
						+ "	3 - Scan for lifeforms on this planet \n"
						+ "	4 - Quit \n");
				int choice;
				
				try {
				    choice = scanner.nextInt();
				} catch (Exception e) {
				    System.out.println("Invalid input. Please enter a number between 1 and 4.");
				    scanner.nextLine(); // Clear the invalid input
				    continue; // Restart the loop
				}

				if (choice < 1 || choice > 4) {
				    System.out.println("Invalid selection. Please choose a valid option.");
				    continue; // Restart the loop
				}
				
				switch (choice) {
		    	
			        case 1:
			            // Implement logic for travel
			        	locationIndex = travel(scanner, ship, locationIndex, solarSystem);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			        	break;
			
			        case 2:
			            // capitan scans the planet for resources
			        	((Capitan) crew.get(0)).action(crew, ship, solarSystem, locationIndex);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			            break;
			
			        case 3:
			            // Implement logic for lifeform scan
			        	((SecurityOfficer) crew.get(1)).action(crew, ship, solarSystem, locationIndex);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			            break;
			
			        case 4:
			            // Implement logic for break out of game entirely
			        	System.out.println("Exiting the game...");
			        	gameExit = true;
			            break;
			
			        default:
			            // TODO: Handle input error
			
			            break;
				}	
				//break;
			}
			
		// 3. GAME END
			scanner.close();
			System.out.println("GAME OVER");
			
	}

	private static void testcase1() { // (ship starts with 10 fuel)
		
		// 1. GAME INITIALIZATION
			
			//OBJECTS
			List<CrewMember> crew = new ArrayList<>();
			List<Planet> solarSystem = new ArrayList<>();
	        Scanner scanner = new Scanner(System.in);
	        RandomEvent event;
	        Random dice = new Random();
			//				shipName, fuelLevel(Liters), cargoCapacity(slots), hullIntegrity(%)
			Starship ship = new Starship("SS Latrexa", 10, 10, 100);
			//				 name, strength(attkPwr), intellegence(x/10), agility(x/10), skill(x/20), health(%)
			CrewMember spock = new Capitan("Spock", 25, 8, 6, 18, 100);
			CrewMember travis = new SecurityOfficer("Travis", 60, 5, 9, 16, 100);
			CrewMember adam = new Engineer("Adam", 10, 9, 3, 20, 100);
			CrewMember taylor = new Scientist("Taylor", 15, 8, 4, 19, 100);
			//						planet name, description
			Planet neptune = new Planet("Neptune", "A storm-ridden gas giant with an endless sea of swirling green and violet "
					+ "clouds. The planet's gravity is so intense that its core is rumored to be a crystalline network of "
					+ "compressed elements, sought after for advanced technology. Lightning arcs across the skies, and "
					+ "floating mining stations cling perilously to its atmosphere.");
			Planet saturn = new Planet("Saturn", "A dazzling desert world with golden sands that shimmer under "
					+ "twin suns. Beneath its surface lie vast caverns filled with bioluminescent flora and crystalline "
					+ "rivers. The nomadic inhabitants harvest \"sunstones,\" rare minerals that store solar energy, "
					+ "making the planet a hub for energy traders.");
			Planet venus = new Planet("Venus", "A frozen tundra planet covered in glaciers and jagged ice peaks. "
					+ "Aurora-like light displays dance across the sky, generated by the planet's magnetized core. "
					+ "Ancient ruins buried deep within the ice suggest a long-lost civilization, and explorers "
					+ "come in search of the mysterious relics.");
			Planet mars = new Planet("Mars", "A lush jungle planet teeming with exotic, bioluminescent "
					+ "plants and colossal, sentient fungi. Its dense atmosphere glows faintly at night, "
					+ "illuminating the surface with hues of blue and purple. The native species, Kaelvans, "
					+ "are telepathic and fiercely protective of the planet’s natural balance.");
			Planet pluto = new Planet("Pluto", "A volcanic world with rivers of molten lava crisscrossing its "
					+ "surface. Ash clouds obscure its sky, and massive geysers release superheated steam. Despite its "
					+ "hostile environment, Vorrakis is rich in valuable ores and is home to fire-resistant creatures "
					+ "that thrive in the extreme heat.");

			//VARIABLES
			int locationIndex = 0;
			boolean gameExit = false;
	        String[] eventTypes = {"Plague", "Hull Damage", "Resource Theft", "Solar Flare"};
			
			//PRE-GAME ROUTINES
			crew.add(spock);
			crew.add(travis);
			crew.add(adam);
			crew.add(taylor);
			solarSystem.add(neptune);
			solarSystem.add(saturn);
			solarSystem.add(venus);
			solarSystem.add(mars);
			solarSystem.add(pluto);
			
		// 2. GAME-UPDATE LOOP
			
			System.out.println("Let your space adventure begin! All abourd the " + ship.getShipName() + "! \n");
			
			while (gameContinue((ArrayList<CrewMember>) crew, ship) && gameExit==false) {
				
				System.out.println(displayStatus(crew, ship, solarSystem, locationIndex));
				
				System.out.println("What would you like to do?: \n"
						+ "	1 - Travel to another Planet \n"
						+ "	2 - Scan for resources on this planet \n"
						+ "	3 - Scan for lifeforms on this planet \n"
						+ "	4 - Quit \n");
				int choice;
				
				try {
				    choice = scanner.nextInt();
				} catch (Exception e) {
				    System.out.println("Invalid input. Please enter a number between 1 and 4.");
				    scanner.nextLine(); // Clear the invalid input
				    continue; // Restart the loop
				}

				if (choice < 1 || choice > 4) {
				    System.out.println("Invalid selection. Please choose a valid option.");
				    continue; // Restart the loop
				}
				
				switch (choice) {
		    	
			        case 1:
			            // Implement logic for travel
			        	locationIndex = travel(scanner, ship, locationIndex, solarSystem);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			        	break;
			
			        case 2:
			            // capitan scans the planet for resources
			        	((Capitan) crew.get(0)).action(crew, ship, solarSystem, locationIndex);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			            break;
			
			        case 3:
			            // Implement logic for lifeform scan
			        	((SecurityOfficer) crew.get(1)).action(crew, ship, solarSystem, locationIndex);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			            break;
			
			        case 4:
			            // Implement logic for break out of game entirely
			        	System.out.println("Exiting the game...");
			        	gameExit = true;
			            break;
			
			        default:
			            // TODO: Handle input error
			
			            break;
				}	
				//break;
			}
			
		// 3. GAME END
			scanner.close();
			System.out.println("GAME OVER");
			
	}

	private static void testcase0() { // normal operation
		
		// 1. GAME INITIALIZATION
			
			//OBJECTS
			List<CrewMember> crew = new ArrayList<>();
			List<Planet> solarSystem = new ArrayList<>();
	        Scanner scanner = new Scanner(System.in);
	        RandomEvent event;
	        Random dice = new Random();
			//				shipName, fuelLevel(Liters), cargoCapacity(slots), hullIntegrity(%)
			Starship ship = new Starship("SS Latrexa", 1000, 10, 100);
			//				 name, strength(attkPwr), intellegence(x/10), agility(x/10), skill(x/20), health(%)
			CrewMember spock = new Capitan("Spock", 25, 8, 6, 18, 100);
			CrewMember travis = new SecurityOfficer("Travis", 60, 5, 9, 16, 100);
			CrewMember adam = new Engineer("Adam", 10, 9, 3, 20, 100);
			CrewMember taylor = new Scientist("Taylor", 15, 8, 4, 19, 100);
			//						planet name, description
			Planet neptune = new Planet("Neptune", "A storm-ridden gas giant with an endless sea of swirling green and violet "
					+ "clouds. The planet's gravity is so intense that its core is rumored to be a crystalline network of "
					+ "compressed elements, sought after for advanced technology. Lightning arcs across the skies, and "
					+ "floating mining stations cling perilously to its atmosphere.");
			Planet saturn = new Planet("Saturn", "A dazzling desert world with golden sands that shimmer under "
					+ "twin suns. Beneath its surface lie vast caverns filled with bioluminescent flora and crystalline "
					+ "rivers. The nomadic inhabitants harvest \"sunstones,\" rare minerals that store solar energy, "
					+ "making the planet a hub for energy traders.");
			Planet venus = new Planet("Venus", "A frozen tundra planet covered in glaciers and jagged ice peaks. "
					+ "Aurora-like light displays dance across the sky, generated by the planet's magnetized core. "
					+ "Ancient ruins buried deep within the ice suggest a long-lost civilization, and explorers "
					+ "come in search of the mysterious relics.");
			Planet mars = new Planet("Mars", "A lush jungle planet teeming with exotic, bioluminescent "
					+ "plants and colossal, sentient fungi. Its dense atmosphere glows faintly at night, "
					+ "illuminating the surface with hues of blue and purple. The native species, Kaelvans, "
					+ "are telepathic and fiercely protective of the planet’s natural balance.");
			Planet pluto = new Planet("Pluto", "A volcanic world with rivers of molten lava crisscrossing its "
					+ "surface. Ash clouds obscure its sky, and massive geysers release superheated steam. Despite its "
					+ "hostile environment, Vorrakis is rich in valuable ores and is home to fire-resistant creatures "
					+ "that thrive in the extreme heat.");

			//VARIABLES
			int locationIndex = 0;
			boolean gameExit = false;
	        String[] eventTypes = {"Plague", "Hull Damage", "Resource Theft", "Solar Flare"};
			
			//PRE-GAME ROUTINES
			crew.add(spock);
			crew.add(travis);
			crew.add(adam);
			crew.add(taylor);
			solarSystem.add(neptune);
			solarSystem.add(saturn);
			solarSystem.add(venus);
			solarSystem.add(mars);
			solarSystem.add(pluto);
			
		// 2. GAME-UPDATE LOOP
			
			System.out.println("Let your space adventure begin! All abourd the " + ship.getShipName() + "! \n");
			
			while (gameContinue((ArrayList<CrewMember>) crew, ship) && !gameExit) {
				
				System.out.println(displayStatus(crew, ship, solarSystem, locationIndex));
				
				System.out.println("What would you like to do?: \n"
						+ "	1 - Travel to another Planet \n"
						+ "	2 - Scan for resources on this planet \n"
						+ "	3 - Scan for lifeforms on this planet \n"
						+ "	4 - Quit \n");
				int choice;
				
				try {
				    choice = scanner.nextInt();
				} catch (Exception e) {
				    System.out.println("Invalid input. Please enter a number between 1 and 4.");
				    scanner.nextLine(); // Clear the invalid input
				    continue; // Restart the loop
				}

				if (choice < 1 || choice > 4) {
				    System.out.println("Invalid selection. Please choose a valid option.");
				    continue; // Restart the loop
				}
				
				switch (choice) {
		    	
			        case 1:
			            // Implement logic for travel
			        	locationIndex = travel(scanner, ship, locationIndex, solarSystem);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			        	break;
			
			        case 2:
			            // capitan scans the planet for resources
			        	((Capitan) crew.get(0)).action(crew, ship, solarSystem, locationIndex);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			            break;
			
			        case 3:
			            // Implement logic for lifeform scan
			        	((SecurityOfficer) crew.get(1)).action(crew, ship, solarSystem, locationIndex);
			        	if ((dice.nextInt(100) + 1) == 0) { // 1% chance of triggering an event
	                        event = new RandomEvent(eventTypes[dice.nextInt(eventTypes.length)], "A random travel event occurred!");
	                        event.triggerEvent(event.getEventType(), ship, crew);
	                    }
			            break;
			
			        case 4:
			            // Implement logic for break out of game entirely
			        	System.out.println("Exiting the game...");
			        	gameExit = true;
			            break;
			
			        default:
			            // TODO: Handle input error
			
			            break;
				}	
				//break;
			}
			
		// 3. GAME END
			scanner.close();
			System.out.println("GAME OVER");
			
	}
	
	public static boolean gameContinue(ArrayList<CrewMember> crew, Starship ship) {
		int condition = 0;
		// Check if at least one crew member is alive
	    for (CrewMember member : crew) {
	        if (member.getHealth() <= 0) {
	            condition++;
	        }
	    }

	    if ( condition == 4 || ship.getFuelLevel() <= 0 || ship.getHullIntegrity() <= 0) {
	        return false; // Game ends if any conditions are met
	    }

	    return true; // Game continues otherwise
	}
	
	public static String displayStatus(List<CrewMember> crew, Starship ship, List<Planet> solarSystem, int locationIndex) {
		return "\nCURRENT LOCATION: " + solarSystem.get(locationIndex) + "\n\n"
			 + crew.get(0).getName() + "'s Health: " + crew.get(0).getHealth() + "\n"
			 + crew.get(1).getName() + "'s Health: " + crew.get(1).getHealth() + "\n"
			 + crew.get(2).getName() + "'s Health: " + crew.get(2).getHealth() + "\n"
			 + crew.get(3).getName() + "'s Health: " + crew.get(3).getHealth() + "\n\n"
			 + ship.getShipName() + "'s Fuel Level: " + ship.getFuelLevel() + "\n"
			 + ship.getShipName() + "'s Hull Integrity: " + ship.getHullIntegrity() + "\n";
	}
	
	public static int travel(Scanner scanner, Starship ship, int locationIndex, List<Planet> solarSystem) {
				
		System.out.println("Where would you like to travel?: \n"
				+ "	0 - Neptune \n"
				+ "	1 - Saturn \n"
				+ "	2 - Venus \n"
				+ "	3 - Mars \n"
				+ "	4 - Pluto \n");
		int planetChoice = 0;
		
		try {
		    planetChoice = scanner.nextInt();
		    if (planetChoice < 0 || planetChoice >= solarSystem.size()) {
		        System.out.println("Invalid planet selection. Please select a valid option.");
		        //break; // Exit travel function
		    }
		} catch (Exception e) {
		    System.out.println("Invalid input. Please enter a number between 0 and 4.");
		    scanner.nextLine(); // Clear invalid input
		    //break; // Exit travel function
		}
		
		int cost = Math.abs((planetChoice - locationIndex) * 10);
		
		if(cost > ship.getFuelLevel()) {
			System.out.println("Not enough fuel for this jump...");
			return locationIndex;
		}
		
		System.out.println("It costs " + cost + "fuel to jump to this planet, proceed?	(Y / N)");
	    scanner.nextLine(); 
		String confirmation = "";
		
		while (true) {
			confirmation = scanner.nextLine().trim().toUpperCase();
			 if (confirmation.equals("Y")) {
			        System.out.println("Traveling to " + solarSystem.get(planetChoice).getName() + "...");
			        ship.setFuelLevel(ship.getFuelLevel() - cost);
			        locationIndex = planetChoice; // Update location index
			        break;
			    } else if (confirmation.equals("N")) {
			        System.out.println("Canceling space jump...");
			        break;
			    } else {
			        System.out.println("Invalid input. Please enter 'Y' to proceed or 'N' to cancel.");
			    }
		}
		return locationIndex;	
	}

}
